projectriff/node-function-invoker

.gitignore, src/main/node/.gitignore, src/main/node/server.js
=> Honor incoming Content-Type header, limited to what module bodyParser supports

.dockerignore, Dockerfile, build.sh
- copy directory recursively, and omit unwanted folders with .dockerignore
- use a WORKDIR so that app doesn't run in root directory
=> fix Dockerfile to include new lib/app.js

README.adoc, README.md
=> Create a readme

lib/grpc.js, lib/interaction-models.js, server.js, spec/grpcSpec.js, spec/serverSpec.js, spec/support/echo-node-streams.js
We may support other streaming interfaces in the future.
=> Rename 'streaming' interaction model to 'node-streams'

README.md
=> Document streaming functions in the readme

.travis.yml
See https://github.com/greenkeeperio/greenkeeper-lockfile
=> Install greenkeeper-lockfile

.travis.yml, README.md, docs/riff_create_node.md, docs/riff_init_node.md, spec/docsSpec.js
and other readme polish
Issue: projectriff/riff#454
=> Generate docs from riff-cli

samples/square/.gitignore, samples/square/README.adoc, samples/square/square.js
Update function readme for new invoker model
=> Move node riff samples into node invoker

samples/mean/.gitignore, samples/mean/README.adoc, samples/mean/mean.js, samples/mean/package-lock.json, samples/mean/package.json
The function computes the mean for a stream of numbers.
Two npm packages are used:
- simple-statistics to compute the mean
- mississippi to create a transforming node stream
=> Add a streaming sample

node-invoker.yaml, samples/typescript/.gitignore, samples/typescript/README.adoc, samples/typescript/lib/greeter.ts, samples/typescript/package-lock.json, samples/typescript/package.json, samples/typescript/tsconfig.json, server.js, spec/server.spec.js, spec/support/echo-esmodule-transpile.js
Also add support for transpiled ES module interop. Proper ES Module
support is still off on the horizon, but we can handle the common
method for ES Modules that have been transpiled to CommonJS Modules.
=> Add typescript sample function

node-invoker.yaml
=> Swap variables used for artifact in ADD and FUNCTION_URI

.travis.yml, Dockerfile, package-lock.json
=> Upgrade to Node 10

lib/input-unmarshaller.js
=> Do not log payload

npm-shrinkwrap.json, package.json
fixes #117 
Ran `npm install --save-dev grpc-tools`
Now i can do `npm run generate-proto`
=> dev-install grpc-tools

.github/workflows/ci.yaml, lib/streaming-pipeline.js, nvm_test_all.sh, package.json
=> Fix failing test with Node 13

.gitignore, README.md, lib/input-unmarshaller.js, lib/invoker.js, lib/output-marshaller.js, lib/request-reply-promoter.js, lib/streaming-pipeline.js, package.json, server.js, spec/reporters/muted-console-reporter.js, spec/run-tests.js
=> Review logging

.github/workflows/ci.yaml
Relates to https://github.com/projectriff/riff/issues/1385
=> Upgrade to checkout@v2

.github/workflows/ci.yaml
=> Trigger npm publication on tag creation

npm-shrinkwrap.json
See https://github.com/advisories/GHSA-vh95-rmgr-6w4m.
=> Fix minimist CVE-2020-7598

lib/hooks.js
=> Implement hook timeout guard with Promise.race

README.md
=> Clarify hook declaration

lib/streaming-pipeline.js, spec/streaming-pipeline.errors.spec.js
=> Cancel gRPC invocation with official API

lib/content-negotiation.js, lib/errors.js, lib/input-unmarshaller.js, lib/streaming-pipeline.js, npm-shrinkwrap.json, package.json, spec/input-unmarshaller.errors.spec.js, spec/input-unmarshaller.spec.js
=> Honor incoming content-type charset where applicable
