projectriff/node-function-invoker

- src/main/node/lib/app.js
- src/main/node/spec/appSpec.js
Either async or Promised function can now be used in addition to
traditional synchronous functions. Node-style callback functions are
not supported.
```js
// sync
module.exports = name => `Hello ${name}!`;
// promise
module.exports = name => Promise.resolve(`Hello ${name}!`);
// async
module.exports = async name => `Hello ${name}!`;
```
Issue: #7
> Add async function support

- server.js
Previously, the invoker would remain up for about a minute after being
told to scale down before finally exiting. Now the node process will
shutdown the server and exit the process when a shutdown signal is
recieved.
Open HTTP connections are allowed up to 10 seconds to finish before the
process exits.
Fixes: #13
> Quickly and cleanly shutdown the invoker when done

- Dockerfile
- package-lock.json
- package.json
- server.js
- spec/serverSpec.js
- spec/support/destroy-throws.js
- spec/support/destroy-timeout.js
- spec/support/echo.js
- spec/support/init-throws.js
- spec/support/init-timeout.js
- spec/support/lifecycle.js
Some functions need to work with external resources. It's often useful
to setup a connection once and then reuse that connection across
multiple function invocations.
```js
module.exports = async () => {
// function
};
module.exports.$init = async () => {
// setup logic
};
module.exports.$destory = async () => {
// cleanup logic
};
```
The `$init` and `$destory` methods will be invoked once before the
invoker handles messages, and after the invoker has handled its last
message, respectively. The destory method has up to 10 seconds to finish
its work before the process will be exit.
Fixes: #15
Refs: #14
> Lifecycle hooks

- lib/grpc.js
- spec/grpcSpec.js
The Content-Type header can also contain a charset param.
```http
Content-Type: text/plain; charset=utf-8
```
Previously this would cause the gRPC handler to choke. Now the charset
is ignored. In the future we should correctly parse the charset and
decode the payload accordingly. For now, all text content is assumed to
be utf-8.
Fixes: #29
> Handle Content-Type headers with a charset

- lib/grpc.js
Using `stream.on('data', func)` loses backpressure. By using a
transforming stream, backpressure is maintained.
> Maintain backpressure for request-reply model

- README.md
- lib/argument-types.js
- lib/grpc.js
- package-lock.json
- package.json
- server.js
- spec/grpcSpec.js
- spec/serverSpec.js
- spec/support/uppercase-custom-message.js
- spec/support/uppercase-headers.js
- spec/support/uppercase-message.js
- spec/support/uppercase-payload.js
- spec/support/uppercase-produces-message.js
Currently, functions only receive message payloads when the function is
invoked. This is akin to an HTTP server that can only the the entity of
a request, or worse, can only set the entity of a response. Each message
in riff contains headers in addition to the payload.
Now functions can opt-in to receive messages or headers. Payloads are
still available by default.
```js
module.exports = message => {
// validate GitHub WebHook signature
const signature = message.headers.getValue('X-Hub-Signature');
...
};
module.exports.$argumentType = 'message';
```
The [@projectriff/message](https://github.com/projectriff/node-message) repository defines the Message and Headers types that are used. They:
- convert to and from the raw format defined by …
> Allow functions to receive messages or payloads

- node-invoker.yaml
- package-lock.json
- package.json
- spec/version.spec.js
The following files should always contain the same version number:
- package.json
- package-lock.json
- node-invoker.yaml
In addition, these versions should match the tag (when tagged).
Fixes #53
> Add tests to enforce version sameness

- .eslintignore
- server.js
- spec/server.spec.js
Functions define the protocol they expect to be invoked on. The inovker
only needs to start the server for the selected protocol. The function
controller will now set RIFF_FUNCTION_INVOKER_PROTOCOL with the value
of the protocol the sidecar will use to connect to the inovker.
When the RIFF_FUNCTION_INVOKER_PROTOCOL value is set to 'http', the grpc
server doesn't need to start, and vice-versa.
Refs projectriff/riff#549
> Only start the needed protocol server

- LICENSE
- lib/argument-transformers.js
- lib/interaction-models/commons.js
- lib/interaction-models/content-negotiation.js
- lib/interaction-models/index.js
- lib/interaction-models/node-streams.js
- lib/interaction-models/request-reply.js
- lib/protocols/grpc.js
- lib/protocols/http.js
- server.js
- spec/docs.spec.js
- spec/grpc-protocol.spec.js
- spec/http-prototcol.spec.js
- spec/server.spec.js
- spec/version.spec.js
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://www.apache.org/licenses/ ([https](https://www.apache.org/licenses/) result 200).
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
> URL Cleanup

- server.js
- spec/server.spec.js
This is the first of a two part change to remove setting default PORT and HOST values from the image layer inside the [node-function-buildpack](https://github.com/projectriff/node-function-buildpack/blob/master/node/riff_invoker.go#L99-L105), Build phase.  
The builder should only care about building the image and less about server configuration, so this change is to provide default values for the `PORT` and `HOST`, if not already set via ENV vars.
> fix: provide default values for port and host

- npm-shrinkwrap.json
- package.json
Bump all dependencies to the latest. All version changes are semver
compatible. `npm audit` reports no issues.
Also demoted the version to `0.1.1-snapshot` since there are no breaking changes since `0.1.0`.
> Update package versions

- lib/interaction-models/content-negotiation.js
- spec/http-prototcol.spec.js
Allow `application/cloudevents+json` to be accepted and marshalled in the same way  as `application/json`.
https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#3-http-message-mapping
#88 was opened to discuss as well.
> Support structured cloudevents using the JSON event format.

- lib/invoker.js
- lib/request-reply-promoter.js
- lib/streaming-pipeline.js
- spec/helpers/hooks/failing-destroy-hook-streaming-function.js
- spec/helpers/hooks/failing-init-hook-streaming-function.js
- spec/helpers/hooks/simple-lifecycle-streaming-function.js
- spec/helpers/hooks/slow-destroy-hook-streaming-function.js
- spec/helpers/hooks/slow-init-hook-streaming-function.js
- spec/helpers/transformers/invalid-argument-transformer-streaming-function.js
- spec/helpers/transformers/invalid-argument-transformers-streaming-function.js
- spec/helpers/transformers/wrong-arity-argument-transformers-streaming-function.js
- spec/streaming-pipeline.errors.spec.js
Fixes #106 
- Extract request-reply function promotion outside of StreamingPipeline
- Mark promoted functions as `$interactionModel = "node-streams"`
- Throw when trying to build a StreamPipeline with non node-stream
functions. This might be a bit hardcore, but, according to the spec,
`The interaction mode and the arity are required in this case.`
> StreamingPipeline expects "node-streams" functions

- lib/argument-transformer-validator.js
- lib/async.js
- lib/errors.js
- lib/input-unmarshaller.js
- lib/mapping-transform.js
- lib/output-marshaller.js
- lib/request-reply-promoter.js
- lib/riff-error.js
- lib/streaming-pipeline.js
- spec/input-unmarshaller.errors.spec.js
- spec/lifecycle.errors.spec.js
- spec/output-marshaller.errors.spec.js
- spec/streaming-pipeline.errors.spec.js
Includes specific gRPC status errors for unsupported input/output
MIME types (see https://github.com/projectriff/invoker-specification/issues/12
and https://github.com/projectriff/invoker-specification/issues/13).
The invocation is also canceled when an invalid signal sequence
occurs or when the function throws at invocation time.
---
Make sure it includes https://github.com/projectriff/streaming-http-adapter/commit/b1bbbaf30f2e84a0e102fc144b251da108a0d656
```shell
$ FUNCTION_URI=~/node-square/square.js NODE_DEBUG='riff' ./streaming-http-adapter npm --prefix ~/workspace/node-function-invoker start
```
```shell
$ curl http://localhost:8080 -d'4' -H'Content-Type: application/json' -H'Accept:text/zglorbf' -v
[...]
< HTTP/1.1 406 Not Acceptable
< Date: Wed, 05 Feb 2020 14:39:49 GMT
< …
```
> Cancel grpc invocation when sensible

- package.json
Fixes https://github.com/projectriff/node-function-buildpack/issues/127.
Note that this potentially includes Node 11, but it is not a
problem, for several reasons:
- the invoker test suite has no issue with Node 11
- the Node buildpack only offers Node 10 (LTS), 12 (LTS) and 13
(latest) at the time of writing
> Exclude Node 13.

- lib/input-unmarshaller.js
- lib/invoker.js
- lib/mapping-transform.js
- lib/output-marshaller.js
- lib/request-reply-promoter.js
- lib/streaming-pipeline.js
- spec/helpers/factories.js
- spec/helpers/fixed-source.js
- spec/helpers/hooks/simple-lifecycle-streaming-function.js
- spec/input-unmarshaller.errors.spec.js
- spec/input-unmarshaller.spec.js
- spec/lifecycle.errors.spec.js
- spec/lifecycle.spec.js
- spec/mapping-transform.errors.spec.js
- spec/mapping-transform.spec.js
- spec/output-marshaller.errors.spec.js
- spec/output-marshaller.spec.js
- spec/streaming-pipeline.errors.spec.js
- spec/streaming-pipeline.spec.js
riff defined streams are only valid in objectMode. we don't need each
instance to be manually placed into objectMode. Since the stream options
can include unintended behavior, like a transform function, it's safer
to not allow external options to be defined.
> Drop stream options

- .github/workflows/ci.yaml
Fixes #144
Running against latest Node version is blocked by #130.
> Run tests with Node 2 last LTS versions

- lib/mapping-transform.js
- lib/request-reply-promoter.js
- lib/streaming-pipeline.js
- spec/request-reply-promoter.errors.spec.js
Fixes #133.
1. create the following function, e.g. `/tmp/joy_division.js`:
```js
module.exports = (x) => {
if (x === 0) {
throw new Error('Division by zero');
}
return 100 / x;
}
```
or even `/tmp/async_joy_division.js`:
```js
module.exports = async (x) => {
if (x === 0) {
throw new Error('Division by zero');
}
return 100 / x;
}
```
2. point the node invoker to the PR branch
3. build (`make`) and run the [adapter](https://github.com/projectriff/streaming-http-adapter)
```shell
FUNCTION_URI=/tmp/joy_division.js NODE_DEBUG='riff' ./streaming-http-adapter npm --prefix ~/workspace/node-function-invoker start
```
4. send a failing request
```shell
curl http://localhost:8080 -H'Content-Type:application/json' -d'0' -H'Accept:text/plain' -v
```
The request should not hang and a 500 response …
> Fix unhandled promise rejection

- spec/reporters/muted-console-reporter.js
Closes #172 
Technically we could do away with just a count, but I introduced a stack for clarity ¯\_(ツ)_/¯
> Jasmine reporter: do not restore console on exiting nested suites

- lib/content-negotiation.js
- spec/content-negotiation.spec.js
Currently, output that uses a wildcard accept header defaults to plain
text. While this is the most compatible for clients, it returns garbage
when the function returns an object, or something with structure.
JSON, while less understood by clients, is able to handle a wider
variety of function outputs. Ultimately, clients should send an Accept
header to pick the type they actually want.
Refs #180
> Change output content type preference to favor json

- lib/errors.js
- lib/streaming-pipeline.js
- spec/streaming-pipeline.errors.spec.js
grpc returns invalid arg code with error type INVALID_INPUT when encounter unmarshall errors, so that streaming-http-adapter can handle invalid json input as http 400 bad request
> set invalid_input error to grpc status code invalid_arg
